### ISSUE TITLE
Example of the module

### ISSUE THREAD

**Issue by iamlvm** [haraldott/DASH-NS3#1]
Thank for your great contribution to DASH,

I have run your simulation with your given segmentSizes matrix but I got no result from the output.
**Command**: `./waf --run "tcp-stream --simulationId=1 --numberOfClients=3 --adaptationAlgo=panda --segmentDuration=2000000 --segmentSizeFile=scratch/segmentSizes.txt"`

How does the output look?
Please provide an example which similar to this simulation [https://github.com/djvergad/dash](url)
I highly appreciate your help.

**Comment by haraldott** [comment]
The output files can be found in mylogs/algorithmName/numberOfClients.
So in your case it shoud be mylogs/panda/3.
I'll only be able to check properly this in a week, since I'm on holidays at the moment. I'll come back to you for this.

**Comment by haraldott** [comment]
Hi,
I think I might've found the problem here.
The markdown wasn't formatted properly, so the example matrix didn't look right.
Please try again - I have added an example segment size file with 8 quality levels and 221 segments.
