### ISSUE TITLE
no output, unclear build/run instruction

### ISSUE THREAD

**Issue by jamiekris** [haraldott/DASH-NS3#2]
Hi,

So, I tried to insert the given files into a pre-existing NS3 directory, and then ran configure and build.
Following these, I tried the following "./waf --run="tcp-stream simulationId=1 numberOfClients=1 adaptationAlgo=festive segmentDuration=2000000 segmentSizeFile=segmentSizes.txt"".

The program seems to loop until I run out of memory. No output/logs are created. Am I missing something here?

**Comment by haraldott** [comment]
Hi jamiekris
I saw your issue just now because you closed it right away.
The example was missing -- before the parameters.
I fixed the markdown file.
