### ISSUE TITLE
problem at running the code

### ISSUE THREAD

**Issue by zainab-malkawi** [haraldott/DASH-NS3#3]
Hi ,
i would like to thank you for your contribution to DASH,

 I tried the following "./waf --run="tcp-stream simulationId=1 numberOfClients=2 adaptationAlgo=panda segmentDuration=2000000 segmentSizeFile=segmentSizes.txt"". after i insert the given files but the progrram keep running without any output or logs .

i thought it was because the segmentsizes.txt file has a large size maybe ?
can you provide me with small trace file ?

**Comment by haraldott** [comment]
The example was missing '--' before the parameters.
I fixed the markdown file.
