### ISSUE TITLE
Problem using the simulator

### ISSUE THREAD

**Issue by ehsaniranmanesh** [haraldott/DASH-NS3#4]
Hi,
Thank you for sharing your simulator with others.
I am a starter in NS3 and I have just learned it by tutorials.
When I copy your project files (a folder with the name "dash-master") in the "contrib" folder, as you said in the Readme file, and try to build the ns3  with this code :

$ ./waf configure --enable-examples --enable-tests
$ ./waf build

I get an error which says :
**" Could not find a task generator for the name 'ns3-dash-master' "**

When I try  
./waf --run="tcp-stream --simulationId=1 --numberOfClients=3 --adaptationAlgo=panda --segmentDuration=2000000 --segmentSizeFile=contrib/dash/segmentSizes.txt"
I also get the same error.
Can you please exactly explain how can I use your project ?

**Comment by haraldott** [comment]
Please try building like this:
./waf configure
./waf

This should work.

It should also work with your settings, of course, I must've screwed up something with the build settings, but I don't have time to look into it at the moment. I will fix the problem, when I find the time.

**Comment by ghost** [comment]
The issue is because the module's names is "dash" and it is NOT "dash-master". In other words, the folder containing this repo should be named "dash" (same as the module's name)
